AllCops:
  Exclude:
    - 'Gemfile'
    - 'spec/spec_helper.rb'
  NewCops: enable
Metrics/BlockLength:
  Exclude:
    - 'spec/*/*'
Layout/LineLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/game_prompts.rb'
Metrics/ClassLength:
  Exclude:
    - 'lib/game.rb'
    - 'lib/board.rb'